import type { Article } from '../wiki'
import { buildPeople, person, type Person } from './people'

/**
 * Nhà soạn nhạc phương Tây, Trung cổ → thế kỷ 20. Mỗi người là một dòng dữ liệu; trang thời kỳ
 * (bảng theo trường phái, xếp theo năm sinh) và trang riêng của từng người được sinh tự động.
 * Thêm người: thêm một dòng c(...) vào đúng nhóm. Nhóm có dạng "thời kỳ:trường phái". Trang được sinh bởi people.ts.
 */

const c = person

const PERIODS = [
  {
    id: 'med',
    slug: 'thoi-ky-trung-co',
    title: 'Thời kỳ Trung cổ',
    years: '~500–1400',
    intro: `Âm nhạc gắn với nhà thờ và triều đình. Từ thánh ca đơn âm (xem [[ket-cau]]) và [[dieu-thuc|điệu thức nhà thờ]], các nhạc sĩ dần chồng thêm bè để tạo ra phức điệu — khởi đầu của [[doi-am]]. Ký âm trên [[khuong-nhac]] cũng ra đời trong thời kỳ này.`,
    groups: [
      ['chant', 'Thánh ca và lý thuyết thời đầu'],
      ['troubadour', 'Troubadour, trouvère và Minnesinger'],
      ['notredame', 'Trường phái Notre-Dame (Ars antiqua)'],
      ['arsnova', 'Ars nova và Ars subtilior'],
    ],
  },
  {
    id: 'ren',
    slug: 'thoi-ky-phuc-hung',
    title: 'Thời kỳ Phục hưng',
    years: '~1400–1600',
    intro: `Thời kỳ vàng son của phức điệu thanh nhạc. Quãng 3 và quãng 6 trở thành [[thuan-nghich|thuận âm]], các bè được viết cân bằng theo kỹ thuật mô phỏng ([[doi-am]]). Thể loại chính: thánh lễ, motet, madrigal và chanson. Cuối thời kỳ, [[hop-am-ba]] trưởng – thứ dần trở thành trung tâm.`,
    groups: [
      ['burgundy', 'Thời kỳ đầu và trường phái Burgundy'],
      ['flemish', 'Trường phái Franco-Flemish'],
      ['italy', 'Ý — Palestrina và madrigal'],
      ['france', 'Pháp — chanson'],
      ['iberia', 'Tây Ban Nha và Bồ Đào Nha'],
      ['england', 'Anh'],
      ['germany', 'Đức'],
    ],
  },
  {
    id: 'bar',
    slug: 'thoi-ky-baroque',
    title: 'Thời kỳ Baroque',
    years: '~1600–1750',
    intro: `Opera ra đời; hệ thống giọng trưởng – thứ được xác lập, cùng [[chuc-nang-hoa-am|hoà âm chức năng]]. Đặc trưng: [[bass-so|basso continuo]], [[fugue]], [[mo-tien-hoa-am|mô tiến]], [[ky-hieu-hoa-my|hoa mỹ]] phong phú, tương phản to – nhỏ theo từng khối. Thể loại: concerto, tổ khúc, sonata, oratorio, cantata.`,
    groups: [
      ['earlyitaly', 'Baroque sớm ở Ý'],
      ['germany17', 'Đức – Áo thế kỷ 17'],
      ['france', 'Pháp'],
      ['england', 'Anh'],
      ['lateitaly', 'Hậu Baroque ở Ý'],
      ['lategermany', 'Đỉnh cao Baroque Đức – Áo'],
    ],
  },
  {
    id: 'cla',
    slug: 'thoi-ky-co-dien',
    title: 'Thời kỳ Cổ điển',
    years: '~1750–1820',
    intro: `Phong cách trong sáng, cân đối: giai điệu có đệm ([[ket-cau|chủ điệu]], bass Alberti), [[cau-nhac]] đối xứng, [[hinh-thuc-sonata]] trở thành khuôn mẫu cho sonata, giao hưởng, tứ tấu và concerto (xem [[the-loai]]). Đàn fortepiano thay thế harpsichord.`,
    groups: [
      ['galant', 'Tiền cổ điển, galant và Mannheim'],
      ['vienna', 'Trường phái Cổ điển Vienna'],
      ['europe', 'Các trung tâm khác ở châu Âu'],
    ],
  },
  {
    id: 'rom',
    slug: 'thoi-ky-lang-man',
    title: 'Thời kỳ Lãng mạn',
    years: '~1820–1910',
    intro: `Cảm xúc cá nhân và kịch tính lên ngôi. [[hoa-am-cromatic|Hoà âm cromatic]], [[trung-am-cromatic]], [[nhip-do|rubato]]; dàn nhạc mở rộng; tiểu phẩm piano (nocturne, ballade, étude — xem [[the-loai]]). Cuối thế kỷ 19, các trường phái **dân tộc** đưa dân ca và [[dieu-thuc|điệu thức]] của quê hương vào âm nhạc.`,
    groups: [
      ['early', 'Lãng mạn sớm và trung kỳ'],
      ['opera', 'Opera và operetta'],
      ['german', 'Hậu Lãng mạn Đức – Áo'],
      ['france', 'Pháp'],
      ['russia', 'Nga'],
      ['national', 'Các trường phái dân tộc'],
      ['americas', 'Anh và châu Mỹ'],
    ],
  },
  {
    id: 'm20',
    slug: 'thoi-ky-the-ky-20',
    title: 'Thế kỷ 20',
    years: '1900–2000',
    intro: `Thời kỳ đa dạng nhất: [[an-tuong|ấn tượng]], [[phi-dieu-tinh|phi điệu tính]] và [[ky-thuat-12-am]], tân cổ điển, âm nhạc dân tộc mới, [[nhip-hon-hop|nhịp lẻ]], [[da-dieu-tinh]], [[am-cum]], âm nhạc điện tử, ngẫu nhiên, [[toi-gian]], cùng sự giao thoa với jazz và nhạc phim. Danh sách gồm những người có sự nghiệp chính trong thế kỷ 20.`,
    groups: [
      ['impressionism', 'Ấn tượng và Pháp đầu thế kỷ'],
      ['vienna2', 'Trường phái Vienna thứ hai'],
      ['russia', 'Nga và Liên Xô'],
      ['neoclassical', 'Tân cổ điển và nhóm Les Six'],
      ['national', 'Âm nhạc dân tộc thế kỷ 20'],
      ['britain', 'Anh'],
      ['america', 'Mỹ'],
      ['avantgarde', 'Tiên phong sau 1945'],
      ['minimal', 'Tối giản, tâm linh và hậu hiện đại'],
      ['film', 'Nhạc phim'],
    ],
  },
] as const

const COMPOSERS: Person[] = [
  // ── Trung cổ ──
  c('Guido d\'Arezzo', 'k. 991–sau 1033', 'Ý', 'med:chant', 'Nhà lý thuyết, cha đẻ của khuông nhạc 4 dòng và hệ thống đọc nốt Ut–Re–Mi (solmization).', ['Micrologus (khảo luận)'], { topics: ['khuong-nhac', 'not-nhac', 'xuong-am'], wiki: 'Guido_of_Arezzo' }),
  c('Hildegard von Bingen', '1098–1179', 'Đức', 'med:chant', 'Nữ tu viện trưởng, nhà thần bí; một trong những nhà soạn nhạc đầu tiên được biết tên với khối lượng thánh ca lớn.', ['Ordo Virtutum', 'Symphonia armonie celestium revelationum'], { topics: ['ket-cau', 'dieu-thuc'], wiki: 'Hildegard_of_Bingen' }),
  c('Bernart de Ventadorn', 'k. 1130–k. 1190', 'Pháp', 'med:troubadour', 'Troubadour nổi tiếng nhất, viết những bài tình ca bằng tiếng Occitan.', ['Can vei la lauzeta mover']),
  c('Comtessa de Dia', 'thế kỷ 12', 'Pháp', 'med:troubadour', 'Nữ troubadour (trobairitz) duy nhất còn lưu lại một bài hát có cả nhạc.', ['A chantar m\'er de so qu\'eu no volria'], { wiki: 'Comtessa_de_Dia' }),
  c('Walther von der Vogelweide', 'k. 1170–k. 1230', 'Đức', 'med:troubadour', 'Minnesinger (người hát tình ca cung đình Đức) nổi tiếng nhất.', ['Palästinalied']),
  c('Thibaut de Champagne', '1201–1253', 'Pháp', 'med:troubadour', 'Vua xứ Navarre và trouvère có nhiều bài hát còn lưu giữ nhất.', ['Chansons courtoises'], { wiki: 'Theobald_I_of_Navarre' }),
  c('Adam de la Halle', 'k. 1240–k. 1288', 'Pháp', 'med:troubadour', 'Trouvère vừa viết đơn âm vừa viết phức điệu; tác giả vở nhạc kịch thế tục sớm nhất.', ['Le Jeu de Robin et Marion']),
  c('Léonin', 'k. 1150–k. 1201', 'Pháp', 'med:notredame', 'Nhạc sĩ đầu tiên của trường phái Notre-Dame, gắn với tuyển tập organum hai bè.', ['Magnus liber organi'], { topics: ['ket-cau', 'doi-am'] }),
  c('Pérotin', 'hoạt động k. 1200', 'Pháp', 'med:notredame', 'Mở rộng organum lên ba, bốn bè — những tác phẩm phức điệu đồ sộ đầu tiên.', ['Viderunt omnes', 'Sederunt principes'], { topics: ['ket-cau', 'doi-am'] }),
  c('Franco của Köln', 'giữa thế kỷ 13', 'Đức', 'med:notredame', 'Nhà lý thuyết đặt nền móng cho ký hiệu trường độ (ký âm mensural).', ['Ars cantus mensurabilis (khảo luận)'], { topics: ['truong-do'], wiki: 'Franco_of_Cologne' }),
  c('Philippe de Vitry', '1291–1361', 'Pháp', 'med:arsnova', 'Nhà thơ, giám mục và nhà lý thuyết; khảo luận của ông đặt tên cho phong cách Ars nova.', ['Ars nova (khảo luận)', 'Các motet isorhythmic'], { topics: ['truong-do'] }),
  c('Guillaume de Machaut', 'k. 1300–1377', 'Pháp', 'med:arsnova', 'Nhà soạn nhạc lớn nhất thế kỷ 14; viết thánh lễ phức điệu hoàn chỉnh đầu tiên của một tác giả.', ['Messe de Nostre Dame', 'Ma fin est mon commencement'], { short: 'Machaut', topics: ['doi-am', 'doi-am-kep'] }),
  c('Jacopo da Bologna', 'hoạt động 1340–1386', 'Ý', 'med:arsnova', 'Một trong những bậc thầy đầu tiên của Trecento (Ars nova Ý), nổi bật với madrigal.', ['Non al suo amante']),
  c('Francesco Landini', 'k. 1325–1397', 'Ý', 'med:arsnova', 'Nhạc sĩ organ mù, bậc thầy ballata; "kết Landini" được đặt theo tên ông.', ['Ecco la primavera'], { topics: ['cau-ket'] }),
  c('Solage', 'cuối thế kỷ 14', 'Pháp', 'med:arsnova', 'Đại diện của Ars subtilior — phong cách nhịp điệu phức tạp bậc nhất trước thế kỷ 20.', ['Fumeux fume par fumee'], { topics: ['da-nhip'] }),
  c('Baude Cordier', 'k. 1380–k. 1440', 'Pháp', 'med:arsnova', 'Nổi tiếng với các bản nhạc viết theo hình (hình trái tim, vòng tròn) thời Ars subtilior.', ['Belle, bonne, sage', 'Tout par compas'], { topics: ['doi-am-kep'] }),
  c('Johannes Ciconia', 'k. 1370–1412', 'Vlaanderen (Bỉ)', 'med:arsnova', 'Người Vlaanderen làm việc ở Ý, cầu nối giữa Ars nova Ý – Pháp và Phục hưng.', ['O rosa bella', 'Una panthera']),

  // ── Phục hưng ──
  c('Leonel Power', 'k. 1380–1445', 'Anh', 'ren:burgundy', 'Một trong những người tiên phong thánh lễ theo chu kỳ dựa trên một cantus firmus.', ['Missa Alma redemptoris mater']),
  c('John Dunstable', 'k. 1390–1453', 'Anh', 'ren:burgundy', 'Mang "âm thanh Anh" giàu quãng 3 và 6 sang lục địa, mở đường cho Phục hưng.', ['Quam pulchra es', 'Veni sancte spiritus'], { topics: ['thuan-nghich'] }),
  c('Guillaume Du Fay', 'k. 1397–1474', 'Pháp', 'ren:burgundy', 'Nhà soạn nhạc hàng đầu thế kỷ 15, bậc thầy thánh lễ chu kỳ và motet.', ['Nuper rosarum flores', 'Missa L\'homme armé', 'Missa Se la face ay pale'], { short: 'Du Fay' }),
  c('Gilles Binchois', 'k. 1400–1460', 'Vlaanderen (Bỉ)', 'ren:burgundy', 'Nhạc sĩ triều đình Burgundy, bậc thầy chanson trữ tình.', ['De plus en plus', 'Filles à marier']),
  c('Johannes Ockeghem', 'k. 1410–1497', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Bậc thầy đối âm với những bè dài liên tục; viết bản Requiem phức điệu cổ nhất còn lại.', ['Missa prolationum', 'Requiem'], { topics: ['doi-am-kep'] }),
  c('Antoine Busnois', 'k. 1430–1492', 'Pháp', 'ren:flemish', 'Nhạc sĩ triều đình Burgundy, nổi tiếng với chanson và motet.', ['Anthoni usque limina', 'Je ne puis vivre ainsy']),
  c('Josquin des Prez', 'k. 1450–1521', 'Pháp', 'ren:flemish', 'Nhà soạn nhạc được ngưỡng mộ nhất thời Phục hưng; mô phỏng giữa các bè trở thành nguyên tắc chủ đạo.', ['Ave Maria… virgo serena', 'Missa Pange lingua', 'Mille regretz'], { short: 'Josquin', topics: ['doi-am', 'motif'] }),
  c('Heinrich Isaac', 'k. 1450–1517', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Làm việc ở Florence và triều đình Habsburg; viết chu kỳ thánh ca đồ sộ.', ['Innsbruck, ich muss dich lassen', 'Choralis Constantinus']),
  c('Pierre de la Rue', 'k. 1452–1518', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Nhạc sĩ triều đình Habsburg – Burgundy, nổi bật với âm vực trầm và canon.', ['Requiem', 'Missa L\'homme armé'], { topics: ['doi-am-kep'] }),
  c('Jacob Obrecht', 'k. 1457–1505', 'Hà Lan', 'ren:flemish', 'Bậc thầy thánh lễ cantus firmus với cấu trúc toán học chặt chẽ.', ['Missa Maria zart', 'Missa Sub tuum presidium']),
  c('Jean Mouton', 'k. 1459–1522', 'Pháp', 'ren:flemish', 'Nhạc sĩ cung đình Pháp, nổi tiếng với motet và canon.', ['Nesciens mater']),
  c('Adrian Willaert', 'k. 1490–1562', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Chỉ huy nhạc ở nhà thờ San Marco (Venice), người sáng lập trường phái Venice và kỹ thuật hai dàn hợp xướng.', ['Musica nova', 'Salmi spezzati']),
  c('Nicolas Gombert', 'k. 1495–k. 1560', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Kết cấu mô phỏng dày đặc liên tục, đặc trưng giữa thế kỷ 16.', ['Magnificat', 'Missa Tempore paschali']),
  c('Jacques Arcadelt', 'k. 1507–1568', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Một trong những người tạo nên madrigal Ý thời đầu.', ['Il bianco e dolce cigno']),
  c('Jacobus Clemens non Papa', 'k. 1510–k. 1556', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Nổi tiếng với các thánh vịnh tiếng Hà Lan (Souterliedekens) và motet.', ['Souterliedekens']),
  c('Cipriano de Rore', 'k. 1515–1565', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Madrigal giàu cromatic và biểu cảm, ảnh hưởng lớn tới Monteverdi.', ['Da le belle contrade'], { topics: ['hoa-am-cromatic'] }),
  c('Philippe de Monte', '1521–1603', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Một trong những nhà soạn madrigal nhiều nhất mọi thời đại (hơn 1.100 bài).', ['Madrigali spirituali']),
  c('Orlande de Lassus', '1532–1594', 'Vlaanderen (Bỉ)', 'ren:flemish', 'Nhà soạn nhạc đa năng và nổi tiếng nhất cuối thế kỷ 16, hơn 2.000 tác phẩm ở mọi thể loại.', ['Lagrime di San Pietro', 'Prophetiae Sibyllarum'], { short: 'Lassus' }),
  c('Costanzo Festa', 'k. 1485–1545', 'Ý', 'ren:italy', 'Nhà soạn nhạc Ý nổi bật nhất đầu thế kỷ 16, góp phần hình thành madrigal.', ['Te Deum']),
  c('Giovanni Pierluigi da Palestrina', 'k. 1525–1594', 'Ý', 'ren:italy', 'Biểu tượng của phức điệu thánh nhạc trong sáng; phong cách của ông trở thành chuẩn mực dạy đối âm.', ['Missa Papae Marcelli', 'Sicut cervus'], { short: 'Palestrina', topics: ['doi-am', 'doi-am-5-loai', 'thuan-nghich'] }),
  c('Andrea Gabrieli', 'k. 1532–1585', 'Ý', 'ren:italy', 'Nhạc sĩ organ San Marco, phát triển phong cách đa dàn hợp xướng Venice.', ['Ricercari', 'Concerti']),
  c('Giaches de Wert', '1535–1596', 'Vlaanderen (Bỉ)', 'ren:italy', 'Làm việc tại Mantua; madrigal kịch tính dọn đường cho Monteverdi.', ['Giunto alla tomba']),
  c('Luca Marenzio', '1553–1599', 'Ý', 'ren:italy', 'Bậc thầy madrigal với kỹ thuật "vẽ chữ bằng nhạc".', ['Solo e pensoso']),
  c('Giovanni Gabrieli', 'k. 1555–1612', 'Ý', 'ren:italy', 'Cháu của Andrea; nhạc kèn đồng và hợp xướng nhiều dàn, ghi chỉ dẫn cường độ sớm nhất.', ['Sonata pian\' e forte', 'Canzoni e sonate'], { short: 'Giovanni Gabrieli', topics: ['cuong-do'] }),
  c('Carlo Gesualdo', '1566–1613', 'Ý', 'ren:italy', 'Hoàng tử Venosa; madrigal cromatic táo bạo đến mức gây sửng sốt cả người thế kỷ 20.', ['Moro, lasso, al mio duolo', 'Tenebrae Responsoria'], { short: 'Gesualdo', topics: ['hoa-am-cromatic', 'trung-am-cromatic'] }),
  c('Clément Janequin', 'k. 1485–1558', 'Pháp', 'ren:france', 'Chanson mô tả âm thanh (tiếng chim, trận chiến) sinh động.', ['La guerre (La bataille de Marignan)', 'Le chant des oiseaux']),
  c('Claudin de Sermisy', 'k. 1490–1562', 'Pháp', 'ren:france', 'Chanson Paris giản dị, kết cấu hợp âm khối.', ['Tant que vivray'], { topics: ['ket-cau'] }),
  c('Claude Le Jeune', 'k. 1530–1600', 'Pháp', 'ren:france', 'Thử nghiệm "musique mesurée" — nhịp điệu theo trường độ thơ cổ.', ['Le Printemps'], { topics: ['nhip-hon-hop'] }),
  c('Juan del Encina', '1468–1529', 'Tây Ban Nha', 'ren:iberia', 'Nhà thơ – nhạc sĩ, bậc thầy villancico.', ['Oy comamos y bebamos']),
  c('Cristóbal de Morales', 'k. 1500–1553', 'Tây Ban Nha', 'ren:iberia', 'Nhà soạn thánh nhạc Tây Ban Nha nổi tiếng nhất trước Victoria.', ['Missa Mille regretz', 'Parce mihi Domine']),
  c('Luis de Milán', 'k. 1500–k. 1561', 'Tây Ban Nha', 'ren:iberia', 'Tác giả tuyển tập nhạc vihuela đầu tiên được in.', ['El Maestro']),
  c('Antonio de Cabezón', '1510–1566', 'Tây Ban Nha', 'ren:iberia', 'Nhạc sĩ đàn phím mù, bậc thầy biến tấu (diferencias).', ['Diferencias sobre el canto del caballero'], { topics: ['bien-tau'] }),
  c('Francisco Guerrero', '1528–1599', 'Tây Ban Nha', 'ren:iberia', 'Thánh nhạc giàu giai điệu, rất phổ biến ở Tây Ban Nha và châu Mỹ thuộc địa.', ['Missa de la batalla escoutez']),
  c('Tomás Luis de Victoria', '1548–1611', 'Tây Ban Nha', 'ren:iberia', 'Đỉnh cao thánh nhạc Tây Ban Nha, giàu cảm xúc thần bí.', ['Officium defunctorum', 'O magnum mysterium'], { short: 'Victoria' }),
  c('John Taverner', 'k. 1490–1545', 'Anh', 'ren:england', 'Nhà soạn nhạc Anh hàng đầu đầu thế kỷ 16; thánh lễ của ông khởi nguồn thể loại "In nomine".', ['Missa Gloria tibi Trinitas']),
  c('Thomas Tallis', 'k. 1505–1585', 'Anh', 'ren:england', 'Phục vụ bốn đời vua Anh; motet 40 bè là kỳ tích phức điệu.', ['Spem in alium', 'If ye love me'], { short: 'Tallis', topics: ['doi-am'] }),
  c('William Byrd', 'k. 1540–1623', 'Anh', 'ren:england', 'Bậc thầy toàn diện: thánh nhạc, madrigal và nhạc đàn phím virginal.', ['Mass for Four Voices', 'My Ladye Nevells Booke'], { short: 'Byrd', topics: ['bien-tau'] }),
  c('Thomas Morley', '1557–1602', 'Anh', 'ren:england', 'Phổ biến madrigal Ý ở Anh; viết sách giáo khoa âm nhạc nổi tiếng.', ['Now is the month of maying', 'A Plaine and Easie Introduction to Practicall Musicke']),
  c('John Bull', 'k. 1562–1628', 'Anh', 'ren:england', 'Nghệ sĩ virginal điêu luyện, kỹ thuật đàn phím vượt thời đại.', ['Walsingham Variations'], { topics: ['bien-tau'] }),
  c('John Dowland', '1563–1626', 'Anh', 'ren:england', 'Bậc thầy đàn lute và ca khúc u sầu.', ['Flow, my tears', 'Lachrimae']),
  c('Thomas Tomkins', '1572–1656', 'Anh', 'ren:england', 'Một trong những nhà soạn madrigal và nhạc đàn phím cuối cùng của trường phái Anh.', ['When David heard']),
  c('Thomas Weelkes', '1576–1623', 'Anh', 'ren:england', 'Madrigal Anh giàu màu sắc hoà âm.', ['As Vesta was from Latmos hill descending']),
  c('Orlando Gibbons', '1583–1625', 'Anh', 'ren:england', 'Nhạc sĩ organ Hoàng gia; madrigal, anthem và nhạc đàn phím.', ['The Silver Swan', 'This is the record of John']),
  c('Ludwig Senfl', 'k. 1490–1543', 'Thuỵ Sĩ', 'ren:germany', 'Nhà soạn nhạc hàng đầu nói tiếng Đức đầu thế kỷ 16, nổi bật với Lied phức điệu.', ['Das G\'läut zu Speyer']),
  c('Hans Leo Hassler', '1564–1612', 'Đức', 'ren:germany', 'Mang phong cách Venice về Đức; giai điệu của ông thành thánh ca Passion.', ['Mein G\'müt ist mir verwirret']),
  c('Michael Praetorius', '1571–1621', 'Đức', 'ren:germany', 'Nhà soạn nhạc và học giả; bộ sách Syntagma musicum là tư liệu quý về nhạc cụ thời đó.', ['Terpsichore', 'Es ist ein Ros entsprungen (phối)']),

  // ── Baroque ──
  c('Giulio Caccini', '1551–1618', 'Ý', 'bar:earlyitaly', 'Thành viên Camerata Florence; định hình phong cách độc xướng có bè trầm (monody).', ['Le nuove musiche', 'Amarilli, mia bella'], { topics: ['bass-so'] }),
  c('Jacopo Peri', '1561–1633', 'Ý', 'bar:earlyitaly', 'Tác giả vở opera sớm nhất còn lưu giữ trọn vẹn.', ['Euridice (1600)']),
  c('Claudio Monteverdi', '1567–1643', 'Ý', 'bar:earlyitaly', 'Cầu nối Phục hưng – Baroque; đưa opera thành loại hình nghệ thuật lớn.', ['L\'Orfeo', 'Vespro della Beata Vergine', 'L\'incoronazione di Poppea'], { short: 'Monteverdi', topics: ['bass-so', 'thuan-nghich'] }),
  c('Salamone Rossi', 'k. 1570–1630', 'Ý', 'bar:earlyitaly', 'Nhạc sĩ Do Thái ở Mantua; tiên phong sonata trio.', ['Sonate, sinfonie', 'Hashirim asher lish\'lomo']),
  c('Girolamo Frescobaldi', '1583–1643', 'Ý', 'bar:earlyitaly', 'Nhạc sĩ organ Thánh đường Thánh Phêrô; bậc thầy toccata và nhạc đàn phím tự do.', ['Fiori musicali', 'Toccate'], { topics: ['nhip-do'] }),
  c('Francesco Cavalli', '1602–1676', 'Ý', 'bar:earlyitaly', 'Nhà soạn opera hàng đầu ở Venice giữa thế kỷ 17.', ['La Calisto', 'Giasone']),
  c('Giacomo Carissimi', '1605–1674', 'Ý', 'bar:earlyitaly', 'Định hình thể loại oratorio.', ['Jephte']),
  c('Barbara Strozzi', '1619–1677', 'Ý', 'bar:earlyitaly', 'Nữ ca sĩ – nhà soạn nhạc in nhiều tác phẩm thế tục nhất thời bấy giờ.', ['Lagrime mie', 'Che si può fare']),
  c('Heinrich Schütz', '1585–1672', 'Đức', 'bar:germany17', 'Nhà soạn nhạc Đức quan trọng nhất trước Bach; mang phong cách Ý về Đức.', ['Musikalische Exequien', 'Symphoniae sacrae'], { short: 'Schütz' }),
  c('Johann Hermann Schein', '1586–1630', 'Đức', 'bar:germany17', 'Cantor Thomaskirche Leipzig (vị trí sau này của Bach).', ['Banchetto musicale', 'Israelsbrünnlein']),
  c('Samuel Scheidt', '1587–1654', 'Đức', 'bar:germany17', 'Bậc thầy organ Bắc Đức, biến tấu trên thánh ca.', ['Tabulatura nova'], { topics: ['bien-tau'] }),
  c('Johann Jakob Froberger', '1616–1667', 'Đức', 'bar:germany17', 'Định hình tổ khúc đàn phím (allemande – courante – sarabande – gigue).', ['Lamentation sur la mort de Ferdinand III', 'Các tổ khúc harpsichord'], { topics: ['the-loai'] }),
  c('Dieterich Buxtehude', 'k. 1637–1707', 'Đan Mạch – Đức', 'bar:germany17', 'Nhạc sĩ organ ở Lübeck; Bach đã đi bộ hơn 400 km để nghe ông chơi.', ['Praeludium Sol thứ BuxWV 149', 'Membra Jesu nostri'], { short: 'Buxtehude', topics: ['ostinato'] }),
  c('Heinrich Ignaz Franz Biber', '1644–1704', 'Áo (Bohemia)', 'bar:germany17', 'Nghệ sĩ violin điêu luyện, dùng kỹ thuật lên dây khác thường (scordatura).', ['Sonate của Mân Côi (Rosary Sonatas)', 'Passacaglia cho violin độc tấu'], { topics: ['ostinato'] }),
  c('Johann Pachelbel', '1653–1706', 'Đức', 'bar:germany17', 'Nhạc sĩ organ, thầy của anh trai Bach; Canon cung Rê là tác phẩm Baroque phổ biến nhất ngày nay.', ['Canon và Gigue cung Rê', 'Hexachordum Apollinis'], { short: 'Pachelbel', topics: ['ostinato', 'vong-hop-am', 'mo-tien-hoa-am'] }),
  c('Johann Kuhnau', '1660–1722', 'Đức', 'bar:germany17', 'Người tiền nhiệm của Bach ở Leipzig; viết sonata đàn phím mô tả câu chuyện Kinh Thánh.', ['Biblische Historien']),
  c('Georg Böhm', '1661–1733', 'Đức', 'bar:germany17', 'Nhạc sĩ organ ở Lüneburg, ảnh hưởng tới Bach thời trẻ.', ['Chorale prelude "Vater unser im Himmelreich"', 'Các partita trên thánh ca']),
  c('Louis Couperin', 'k. 1626–1661', 'Pháp', 'bar:france', 'Nghệ sĩ harpsichord; nổi tiếng với các prélude "không vạch nhịp".', ['Préludes non mesurés'], { topics: ['so-chi-nhip'] }),
  c('Jean-Baptiste Lully', '1632–1687', 'Ý – Pháp', 'bar:france', 'Thống trị âm nhạc triều Louis XIV; tạo ra opera Pháp và overture kiểu Pháp.', ['Armide', 'Le Bourgeois gentilhomme'], { short: 'Lully' }),
  c('Marc-Antoine Charpentier', '1643–1704', 'Pháp', 'bar:france', 'Thánh nhạc Pháp phong phú; Te Deum của ông là nhạc hiệu Eurovision.', ['Te Deum', 'Médée']),
  c('Marin Marais', '1656–1728', 'Pháp', 'bar:france', 'Bậc thầy đàn viola da gamba.', ['Les folies d\'Espagne', 'Pièces de viole'], { topics: ['bien-tau'] }),
  c('Michel-Richard de Lalande', '1657–1726', 'Pháp', 'bar:france', 'Nhạc sĩ nhà nguyện Versailles, bậc thầy grand motet.', ['Symphonies pour les soupers du Roy', 'De profundis']),
  c('André Campra', '1660–1744', 'Pháp', 'bar:france', 'Tạo ra thể loại opéra-ballet.', ['L\'Europe galante']),
  c('Élisabeth Jacquet de La Guerre', '1665–1729', 'Pháp', 'bar:france', 'Thần đồng harpsichord; nữ nhạc sĩ Pháp đầu tiên viết opera.', ['Pièces de clavecin', 'Céphale et Procris']),
  c('François Couperin', '1668–1733', 'Pháp', 'bar:france', '"Couperin vĩ đại"; tiểu phẩm harpsichord giàu hoa mỹ, sách hướng dẫn ngón bấm.', ['Les barricades mystérieuses', 'L\'art de toucher le clavecin'], { short: 'Couperin', topics: ['ky-hieu-hoa-my', 'ngon-bam'] }),
  c('Jean-Philippe Rameau', '1683–1764', 'Pháp', 'bar:france', 'Nhà soạn nhạc và nhà lý thuyết; "Traité de l\'harmonie" (1722) đặt nền cho lý thuyết hợp âm và nốt gốc.', ['Hippolyte et Aricie', 'Les Indes galantes', 'Nouvelles suites de pièces de clavecin'], { short: 'Rameau', topics: ['chuc-nang-hoa-am', 'the-dao-hop-am', 'hop-am-ba'] }),
  c('Jean-Marie Leclair', '1697–1764', 'Pháp', 'bar:france', 'Người sáng lập trường phái violin Pháp.', ['Sonate violin']),
  c('John Blow', '1649–1708', 'Anh', 'bar:england', 'Nhạc sĩ organ Westminster, thầy của Purcell.', ['Venus and Adonis']),
  c('Henry Purcell', '1659–1695', 'Anh', 'bar:england', 'Nhà soạn nhạc Anh vĩ đại nhất thời Baroque; bậc thầy bass lặp.', ['Dido and Aeneas', 'The Fairy-Queen', 'Music for the Funeral of Queen Mary'], { short: 'Purcell', topics: ['ostinato'] }),
  c('Alessandro Stradella', '1643–1682', 'Ý', 'bar:lateitaly', 'Tiên phong concerto grosso và oratorio.', ['San Giovanni Battista']),
  c('Arcangelo Corelli', '1653–1713', 'Ý', 'bar:lateitaly', 'Định hình sonata trio và concerto grosso; mô tiến hoà âm mẫu mực.', ['Concerti grossi Op. 6', 'Sonata "La Folia" Op. 5'], { short: 'Corelli', topics: ['mo-tien-hoa-am', 'bien-tau'] }),
  c('Alessandro Scarlatti', '1660–1725', 'Ý', 'bar:lateitaly', 'Người đứng đầu trường phái opera Napoli; định hình aria da capo.', ['Il Pirro e Demetrio', 'Hơn 600 cantata'], { topics: ['hinh-thuc-am-nhac'] }),
  c('Tomaso Albinoni', '1671–1751', 'Ý', 'bar:lateitaly', 'Concerto cho oboe và đàn dây; "Adagio của Albinoni" thực ra do Remo Giazotto viết năm 1958.', ['Concerti a cinque Op. 9']),
  c('Antonio Vivaldi', '1678–1741', 'Ý', 'bar:lateitaly', 'Linh mục tóc đỏ ở Venice; hơn 500 concerto định hình cấu trúc nhanh – chậm – nhanh.', ['Bốn mùa (Le quattro stagioni)', 'L\'estro armonico', 'Gloria'], { short: 'Vivaldi', topics: ['mo-tien-hoa-am', 'the-loai'] }),
  c('Francesco Durante', '1684–1755', 'Ý', 'bar:lateitaly', 'Thầy dạy quan trọng của trường phái Napoli (partimenti).', ['Magnificat']),
  c('Domenico Scarlatti', '1685–1757', 'Ý', 'bar:lateitaly', 'Con của Alessandro; 555 sonata harpsichord một chương dạng hai đoạn, kỹ thuật táo bạo.', ['Sonata K. 380', 'Sonata K. 141'], { topics: ['hinh-thuc-am-nhac'] }),
  c('Benedetto Marcello', '1686–1739', 'Ý', 'bar:lateitaly', 'Nhà quý tộc Venice, nhà văn và nhà soạn nhạc (Concerto oboe Rê thứ nổi tiếng là của anh trai ông, Alessandro).', ['Estro poetico-armonico (50 thánh vịnh)', 'Il teatro alla moda (bài văn châm biếm opera)']),
  c('Francesco Geminiani', '1687–1762', 'Ý', 'bar:lateitaly', 'Học trò Corelli; viết sách dạy violin có ảnh hưởng lớn.', ['The Art of Playing on the Violin']),
  c('Giuseppe Tartini', '1692–1770', 'Ý', 'bar:lateitaly', 'Nghệ sĩ violin, phát hiện "âm thứ ba" (âm kết hợp) trong âm học.', ['Sonata "Trille du Diable"'], { topics: ['chuoi-boi-am', 'ky-hieu-hoa-my'] }),
  c('Pietro Locatelli', '1695–1764', 'Ý', 'bar:lateitaly', 'Nghệ sĩ violin điêu luyện, tiền thân của Paganini.', ['L\'arte del violino Op. 3']),
  c('Giovanni Battista Pergolesi', '1710–1736', 'Ý', 'bar:lateitaly', 'Mất năm 26 tuổi; opera buffa của ông khởi đầu phong cách galant.', ['Stabat Mater', 'La serva padrona']),
  c('Johann Joseph Fux', '1660–1741', 'Áo', 'bar:lategermany', 'Nhạc trưởng triều Vienna; "Gradus ad Parnassum" (1725) là sách dạy đối âm kinh điển suốt 300 năm.', ['Gradus ad Parnassum', 'Missa Canonica'], { short: 'Fux', topics: ['doi-am-5-loai', 'doi-am'] }),
  c('Jan Dismas Zelenka', '1679–1745', 'Séc (Bohemia)', 'bar:lategermany', 'Làm việc ở Dresden; thánh nhạc với hoà âm và đối âm táo bạo.', ['Missa Dei Patris', 'Sonata cho hai oboe và bassoon']),
  c('Georg Philipp Telemann', '1681–1767', 'Đức', 'bar:lategermany', 'Một trong những nhà soạn nhạc sung sức nhất lịch sử (hơn 3.000 tác phẩm).', ['Tafelmusik', 'Fantasia cho sáo độc tấu', 'Der Tag des Gerichts'], { short: 'Telemann' }),
  c('Christoph Graupner', '1683–1760', 'Đức', 'bar:lategermany', 'Nhạc trưởng Darmstadt; hơn 1.400 cantata.', ['Partita harpsichord']),
  c('Johann David Heinichen', '1683–1729', 'Đức', 'bar:lategermany', 'Viết khảo luận lớn về bass số; làm việc ở Dresden.', ['Der General-Bass in der Composition'], { topics: ['bass-so'] }),
  c('Johann Sebastian Bach', '1685–1750', 'Đức', 'bar:lategermany', 'Đỉnh cao của đối âm và hoà âm Baroque; tác phẩm của ông là nền tảng giáo dục âm nhạc phương Tây.', ['Clavier bình quân (2 tập)', 'Thánh lễ Si thứ', 'Cuộc khổ nạn theo Thánh Matthew', 'Goldberg Variations', 'Brandenburg Concertos', 'Inventions và Sinfonias'], { short: 'Bach', topics: ['fugue', 'doi-am', 'doi-am-kep', 'luat-binh-quan', 'bien-tau', 'dan-giong', 'phan-tich-prelude-do-truong'] }),
  c('George Frideric Handel', '1685–1759', 'Đức – Anh', 'bar:lategermany', 'Sinh ở Đức, nổi danh ở London với opera Ý và oratorio tiếng Anh.', ['Messiah', 'Water Music', 'Music for the Royal Fireworks', 'Giulio Cesare'], { short: 'Handel' }),
  c('Johann Joachim Quantz', '1697–1773', 'Đức', 'bar:lategermany', 'Thầy dạy sáo của vua Frederick Đại đế; sách về cách biểu diễn là tư liệu quý.', ['Versuch einer Anweisung die Flöte traversiere zu spielen']),
  c('Johann Adolph Hasse', '1699–1783', 'Đức', 'bar:lategermany', 'Nhà soạn opera seria được yêu thích nhất châu Âu giữa thế kỷ 18.', ['Cleofide', 'Artaserse']),

  // ── Cổ điển ──
  c('Giovanni Battista Sammartini', 'k. 1700–1775', 'Ý', 'cla:galant', 'Một trong những người viết giao hưởng sớm nhất.', ['Các giao hưởng Milan'], { topics: ['the-loai'] }),
  c('Baldassare Galuppi', '1706–1785', 'Ý', 'cla:galant', 'Cha đẻ của opera buffa Venice; sonata đàn phím phong cách galant.', ['Il filosofo di campagna']),
  c('Wilhelm Friedemann Bach', '1710–1784', 'Đức', 'cla:galant', 'Con trưởng của J.S. Bach, nghệ sĩ organ và người ứng tác tài ba.', ['Polonaise cho đàn phím', 'Fantasia']),
  c('Carl Philipp Emanuel Bach', '1714–1788', 'Đức', 'cla:galant', 'Con thứ của J.S. Bach; phong cách "cảm xúc" (Empfindsamkeit); sách dạy đàn phím ảnh hưởng tới Haydn, Mozart, Beethoven.', ['Versuch über die wahre Art das Clavier zu spielen', 'Sonate Prussia'], { short: 'C.P.E. Bach', topics: ['ngon-bam', 'ky-hieu-hoa-my'] }),
  c('Christoph Willibald Gluck', '1714–1787', 'Đức – Áo', 'cla:galant', 'Cải cách opera: phục vụ kịch tính thay vì phô diễn giọng hát.', ['Orfeo ed Euridice', 'Iphigénie en Tauride'], { short: 'Gluck' }),
  c('Georg Christoph Wagenseil', '1715–1777', 'Áo', 'cla:galant', 'Nhạc sĩ triều Vienna, góp phần hình thành giao hưởng và concerto đàn phím.', ['Concerto harpsichord']),
  c('Johann Stamitz', '1717–1757', 'Séc (Bohemia)', 'cla:galant', 'Lập ra trường phái Mannheim: crescendo dàn nhạc, "tên lửa Mannheim".', ['Giao hưởng Mannheim'], { topics: ['cuong-do'] }),
  c('Leopold Mozart', '1719–1787', 'Đức – Áo', 'cla:galant', 'Cha và thầy của Mozart; sách dạy violin nổi tiếng.', ['Versuch einer gründlichen Violinschule', 'Giao hưởng Đồ chơi (gán cho ông)']),
  c('Johann Christian Bach', '1735–1782', 'Đức – Anh', 'cla:galant', '"Bach London", con út của J.S. Bach; ảnh hưởng trực tiếp tới Mozart thời nhỏ.', ['Sonata Op. 5', 'Giao hưởng Op. 18']),
  c('Joseph Haydn', '1732–1809', 'Áo', 'cla:vienna', '"Cha đẻ của giao hưởng và tứ tấu đàn dây"; định hình hình thức sonata.', ['104 giao hưởng (số 94 "Bất ngờ", số 104 "London")', 'Tứ tấu "Hoàng đế"', 'Oratorio "Sáng thế"'], { short: 'Haydn', topics: ['hinh-thuc-sonata', 'the-loai', 'motif'] }),
  c('Michael Haydn', '1737–1806', 'Áo', 'cla:vienna', 'Em trai Joseph Haydn, thánh nhạc ở Salzburg, thầy của Weber.', ['Requiem Đô thứ']),
  c('Carl Ditters von Dittersdorf', '1739–1799', 'Áo', 'cla:vienna', 'Nghệ sĩ violin và nhà soạn nhạc được yêu thích ở Vienna.', ['Giao hưởng theo Biến hình của Ovid', 'Doktor und Apotheker']),
  c('Johann Baptist Vanhal', '1739–1813', 'Séc (Bohemia)', 'cla:vienna', 'Giao hưởng và concerto rất phổ biến; từng chơi tứ tấu cùng Haydn và Mozart.', ['Concerto contrabass']),
  c('Antonio Salieri', '1750–1825', 'Ý – Áo', 'cla:vienna', 'Nhạc trưởng triều Vienna, thầy của Beethoven, Schubert và Liszt.', ['Tarare', 'Requiem']),
  c('Wolfgang Amadeus Mozart', '1756–1791', 'Áo', 'cla:vienna', 'Thiên tài toàn diện của thời Cổ điển, đỉnh cao ở mọi thể loại.', ['Đám cưới Figaro', 'Don Giovanni', 'Cây sáo thần', 'Giao hưởng số 40 và 41', 'Requiem', 'Sonata K. 331 và K. 545', 'Biến tấu "Ah vous dirai-je, Maman"'], { short: 'Mozart', topics: ['hinh-thuc-sonata', 'bien-tau', 'rondo', 'ket-cau', 'the-loai', 'phan-tich-sonata-k545'] }),
  c('Ludwig van Beethoven', '1770–1827', 'Đức', 'cla:vienna', 'Cầu nối Cổ điển – Lãng mạn; phát triển motif và hình thức sonata đến giới hạn mới.', ['9 giao hưởng', '32 sonata piano ("Ánh trăng", "Pathétique", "Appassionata")', 'Für Elise', 'Missa solemnis', 'Diabelli Variations'], { short: 'Beethoven', topics: ['motif', 'hinh-thuc-sonata', 'rondo', 'cau-nhac', 'hop-am-napoli', 'phan-tich-fur-elise'] }),
  c('Johann Nepomuk Hummel', '1778–1837', 'Áo (Pressburg)', 'cla:vienna', 'Học trò Mozart, nghệ sĩ piano lừng danh; cầu nối tới Chopin.', ['Concerto trumpet', 'Concerto piano La thứ']),
  c('François-Joseph Gossec', '1734–1829', 'Vlaanderen – Pháp', 'cla:europe', 'Người đặt nền cho giao hưởng Pháp và âm nhạc Cách mạng Pháp.', ['Gavotte', 'Marche lugubre']),
  c('Giovanni Paisiello', '1740–1816', 'Ý', 'cla:europe', 'Bậc thầy opera buffa trường phái Napoli.', ['Il barbiere di Siviglia (1782)', 'Nina']),
  c('André Grétry', '1741–1813', 'Vlaanderen – Pháp', 'cla:europe', 'Nhà soạn opéra comique hàng đầu nước Pháp.', ['Richard Cœur-de-lion']),
  c('Luigi Boccherini', '1743–1805', 'Ý', 'cla:europe', 'Nghệ sĩ cello làm việc ở Tây Ban Nha; bậc thầy ngũ tấu đàn dây.', ['Minuet trong Ngũ tấu Op. 11 số 5', 'Concerto cello Si giáng']),
  c('Joseph Bologne, Chevalier de Saint-Georges', '1745–1799', 'Pháp (Guadeloupe)', 'cla:europe', 'Nghệ sĩ violin, kiếm sĩ, nhạc trưởng; nhà soạn nhạc cổ điển gốc Phi nổi tiếng nhất thời ấy.', ['Concerto violin', 'Symphonie concertante']),
  c('Domenico Cimarosa', '1749–1801', 'Ý', 'cla:europe', 'Nhà soạn opera buffa thành công nhất cuối thế kỷ 18.', ['Il matrimonio segreto']),
  c('Muzio Clementi', '1752–1832', 'Ý – Anh', 'cla:europe', '"Cha đẻ của piano"; sonatina và sách luyện ngón vẫn là giáo trình chuẩn.', ['Sonatina Op. 36', 'Gradus ad Parnassum (luyện ngón)'], { short: 'Clementi', topics: ['hinh-thuc-sonata', 'ngon-bam'] }),
  c('Ignaz Pleyel', '1757–1831', 'Áo – Pháp', 'cla:europe', 'Học trò Haydn; sau lập hãng đàn piano Pleyel mà Chopin yêu thích.', ['Các tứ tấu đàn dây']),
  c('Jan Ladislav Dussek', '1760–1812', 'Séc (Bohemia)', 'cla:europe', 'Nghệ sĩ piano lưu diễn, phong cách tiền Lãng mạn.', ['Sonata "Élégie harmonique"']),
  c('Luigi Cherubini', '1760–1842', 'Ý – Pháp', 'cla:europe', 'Giám đốc Nhạc viện Paris; Beethoven coi ông là nhà soạn nhạc đương thời vĩ đại nhất.', ['Médée', 'Requiem Đô thứ']),
  c('Étienne Méhul', '1763–1817', 'Pháp', 'cla:europe', 'Nhà soạn opera thời Cách mạng và Napoleon.', ['Joseph', 'Le chant du départ']),
  c('Anton Diabelli', '1781–1858', 'Áo', 'cla:europe', 'Nhà xuất bản và nhà soạn nhạc; chủ đề valse của ông được Beethoven viết 33 biến tấu.', ['Sonatina Op. 151 và 168'], { topics: ['bien-tau'] }),
  c('Friedrich Kuhlau', '1786–1832', 'Đức – Đan Mạch', 'cla:europe', 'Sonatina piano là giáo trình kinh điển cho học sinh.', ['Sonatina Op. 20 và 55', 'Elverhøj'], { short: 'Kuhlau', topics: ['hinh-thuc-sonata'] }),
  c('Carl Czerny', '1791–1857', 'Áo', 'cla:europe', 'Học trò Beethoven, thầy của Liszt; hàng nghìn bài luyện ngón cho piano.', ['Die Schule der Geläufigkeit Op. 299', 'Op. 740 (Nghệ thuật luyện ngón)', 'Op. 599'], { short: 'Czerny', topics: ['ngon-bam', 'bai-tap-ngon', 'lo-trinh-tac-pham'] }),

  // ── Lãng mạn ──
  c('John Field', '1782–1837', 'Ireland', 'rom:early', 'Người sáng tạo thể loại nocturne cho piano, ảnh hưởng trực tiếp tới Chopin.', ['18 Nocturne'], { topics: ['the-loai'] }),
  c('Niccolò Paganini', '1782–1840', 'Ý', 'rom:early', 'Nghệ sĩ violin huyền thoại; 24 Caprice truyền cảm hứng cho Liszt, Brahms, Rachmaninoff.', ['24 Caprice Op. 1', 'Concerto violin số 1'], { short: 'Paganini', topics: ['bien-tau'] }),
  c('Louis Spohr', '1784–1859', 'Đức', 'rom:early', 'Nghệ sĩ violin, nhạc trưởng; một trong những người đầu tiên dùng đũa chỉ huy.', ['Concerto clarinet', 'Ngũ tấu kèn']),
  c('Carl Maria von Weber', '1786–1826', 'Đức', 'rom:early', 'Khai sinh opera Lãng mạn Đức.', ['Der Freischütz', 'Aufforderung zum Tanz'], { short: 'Weber' }),
  c('Gioachino Rossini', '1792–1868', 'Ý', 'rom:early', 'Bậc thầy opera buffa; "Rossini crescendo" đầy hứng khởi.', ['Người thợ cạo thành Seville', 'William Tell'], { short: 'Rossini', topics: ['cuong-do'] }),
  c('Franz Schubert', '1797–1828', 'Áo', 'rom:early', 'Hơn 600 Lied; giai điệu và chuyển giọng sang trung âm cromatic đặc trưng.', ['Winterreise', 'Giao hưởng "Dang dở"', 'Ngũ tấu "Con cá hồi"', 'Impromptu Op. 90', 'Erlkönig'], { short: 'Schubert', topics: ['trung-am-cromatic', 'the-loai'] }),
  c('Gaetano Donizetti', '1797–1848', 'Ý', 'rom:early', 'Bậc thầy bel canto, hơn 70 opera.', ['Lucia di Lammermoor', 'L\'elisir d\'amore']),
  c('Vincenzo Bellini', '1801–1835', 'Ý', 'rom:early', 'Giai điệu bel canto dài và trữ tình, ảnh hưởng lớn tới Chopin.', ['Norma', 'La sonnambula']),
  c('Hector Berlioz', '1803–1869', 'Pháp', 'rom:early', 'Người cách tân dàn nhạc; giao hưởng có chương trình và "leitmotif" sơ khai (idée fixe).', ['Symphonie fantastique', 'Les Troyens', 'Khảo luận phối khí'], { short: 'Berlioz', topics: ['motif'] }),
  c('Fanny Mendelssohn', '1805–1847', 'Đức', 'rom:early', 'Nghệ sĩ piano và nhà soạn nhạc tài năng, chị gái của Felix; hơn 450 tác phẩm.', ['Das Jahr', 'Tam tấu piano Op. 11'], { wiki: 'Fanny_Mendelssohn' }),
  c('Felix Mendelssohn', '1809–1847', 'Đức', 'rom:early', 'Phục hưng âm nhạc Bach (1829); phong cách Lãng mạn với hình thức Cổ điển.', ['Giấc mộng đêm hè', 'Concerto violin Mi thứ', 'Bài ca không lời', 'Giao hưởng "Ý"'], { short: 'Mendelssohn', topics: ['the-loai'] }),
  c('Frédéric Chopin', '1810–1849', 'Ba Lan – Pháp', 'rom:early', '"Nhà thơ của piano"; gần như toàn bộ tác phẩm viết cho piano, đỉnh cao của rubato và pedal.', ['Nocturne', 'Ballade', '24 Prélude Op. 28', 'Étude Op. 10 và 25', 'Polonaise và Mazurka', 'Fantaisie-Impromptu'], { short: 'Chopin', topics: ['the-loai', 'nhip-do', 'ban-dap', 'ky-hieu-hoa-my', 'da-nhip'] }),
  c('Robert Schumann', '1810–1856', 'Đức', 'rom:early', 'Tiểu phẩm piano giàu tính văn học, Lied, nhà phê bình âm nhạc.', ['Kinderszenen ("Träumerei")', 'Carnaval', 'Dichterliebe', 'Concerto piano La thứ'], { short: 'Schumann', topics: ['the-loai', 'hemiola'] }),
  c('Franz Liszt', '1811–1886', 'Hungary', 'rom:early', 'Nghệ sĩ piano vĩ đại nhất thế kỷ 19; sáng tạo thơ giao hưởng và độc tấu (recital).', ['Hungarian Rhapsodies', 'Sonata Si thứ', 'Liebestraum số 3', 'Études d\'exécution transcendante', 'La campanella'], { short: 'Liszt', topics: ['hoa-am-cromatic', 'trung-am-cromatic', 'the-loai'] }),
  c('Friedrich Burgmüller', '1806–1874', 'Đức – Pháp', 'rom:early', 'Sống ở Paris; các tuyển tập luyện tập của ông là giáo trình piano kinh điển cho học sinh.', ['25 Études faciles et progressives Op. 100', '18 Études Op. 109'], { short: 'Burgmüller', topics: ['lo-trinh-tac-pham', 'dien-dat-cau-nhac'] }),
  c('Stephen Heller', '1813–1888', 'Hungary – Pháp', 'rom:early', 'Nghệ sĩ piano sống ở Paris, bạn của Chopin và Liszt; nổi tiếng với các tuyển tập étude giàu chất trữ tình.', ['30 Études mélodiques et progressives Op. 46', '25 Études Op. 45'], { short: 'Heller', topics: ['lo-trinh-tac-pham'] }),
  c('Charles-Valentin Alkan', '1813–1888', 'Pháp', 'rom:early', 'Nhạc piano cực kỳ khó và độc đáo.', ['Grande sonate "Les quatre âges"', '12 Études Op. 39']),
  c('Clara Schumann', '1819–1896', 'Đức', 'rom:early', 'Một trong những nghệ sĩ piano lớn nhất thế kỷ 19, vợ của Robert Schumann.', ['Concerto piano La thứ', 'Tam tấu piano Op. 17']),
  c('Giacomo Meyerbeer', '1791–1864', 'Đức – Pháp', 'rom:opera', 'Ông hoàng của "grand opéra" Paris.', ['Les Huguenots', 'Robert le diable']),
  c('Richard Wagner', '1813–1883', 'Đức', 'rom:opera', 'Nhạc kịch tổng hợp, leitmotif, hoà âm cromatic mở đường cho thế kỷ 20.', ['Der Ring des Nibelungen', 'Tristan und Isolde', 'Die Meistersinger', 'Parsifal'], { short: 'Wagner', topics: ['hoa-am-cromatic', 'motif', 'phi-dieu-tinh'] }),
  c('Giuseppe Verdi', '1813–1901', 'Ý', 'rom:opera', 'Nhà soạn opera Ý vĩ đại nhất, biểu tượng thống nhất nước Ý.', ['La traviata', 'Rigoletto', 'Aida', 'Otello', 'Requiem'], { short: 'Verdi' }),
  c('Charles Gounod', '1818–1893', 'Pháp', 'rom:opera', 'Opera trữ tình Pháp; "Ave Maria" dựa trên Prelude của Bach.', ['Faust', 'Roméo et Juliette', 'Ave Maria']),
  c('Jacques Offenbach', '1819–1880', 'Đức – Pháp', 'rom:opera', 'Cha đẻ của operetta.', ['Orphée aux enfers ("Can-can")', 'Les contes d\'Hoffmann']),
  c('Johann Strauss II', '1825–1899', 'Áo', 'rom:opera', '"Vua valse".', ['Dòng Danube xanh', 'Die Fledermaus'], { topics: ['so-chi-nhip'] }),
  c('Georges Bizet', '1838–1875', 'Pháp', 'rom:opera', 'Opera Carmen là một trong những vở được diễn nhiều nhất thế giới.', ['Carmen', 'L\'Arlésienne', 'Jeux d\'enfants']),
  c('Arthur Sullivan', '1842–1900', 'Anh', 'rom:opera', 'Cùng Gilbert tạo nên các operetta Anh nổi tiếng.', ['The Mikado', 'The Pirates of Penzance']),
  c('Jules Massenet', '1842–1912', 'Pháp', 'rom:opera', 'Opera trữ tình Pháp cuối thế kỷ 19.', ['Manon', 'Werther', 'Méditation (Thaïs)']),
  c('Ruggero Leoncavallo', '1857–1919', 'Ý', 'rom:opera', 'Đại diện chủ nghĩa hiện thực (verismo).', ['Pagliacci']),
  c('Giacomo Puccini', '1858–1924', 'Ý', 'rom:opera', 'Nhà soạn opera Ý nổi tiếng nhất sau Verdi, giai điệu trữ tình đầy kịch tính.', ['La bohème', 'Tosca', 'Madama Butterfly', 'Turandot'], { short: 'Puccini' }),
  c('Pietro Mascagni', '1863–1945', 'Ý', 'rom:opera', 'Cavalleria rusticana mở đầu trào lưu verismo.', ['Cavalleria rusticana']),
  c('Anton Bruckner', '1824–1896', 'Áo', 'rom:german', 'Nhạc sĩ organ; giao hưởng đồ sộ như những thánh đường âm thanh.', ['Giao hưởng số 4 "Lãng mạn", số 7, số 8', 'Te Deum'], { short: 'Bruckner', topics: ['bass-ngan'] }),
  c('Johannes Brahms', '1833–1897', 'Đức', 'rom:german', 'Kết hợp cảm xúc Lãng mạn với đối âm và hình thức cổ điển; bậc thầy hemiola và biến tấu.', ['4 giao hưởng', 'Requiem Đức', 'Concerto piano số 1 và 2', 'Hungarian Dances', 'Intermezzi Op. 117–119', 'Biến tấu chủ đề Handel'], { short: 'Brahms', topics: ['hemiola', 'bien-tau', 'da-nhip', 'ostinato'] }),
  c('Max Bruch', '1838–1920', 'Đức', 'rom:german', 'Nổi tiếng với concerto violin trữ tình.', ['Concerto violin số 1 Sol thứ', 'Kol Nidrei']),
  c('Engelbert Humperdinck', '1854–1921', 'Đức', 'rom:german', 'Opera cổ tích chịu ảnh hưởng Wagner.', ['Hänsel und Gretel']),
  c('Hugo Wolf', '1860–1903', 'Áo', 'rom:german', 'Bậc thầy Lied với hoà âm cromatic tinh tế.', ['Mörike-Lieder', 'Italienisches Liederbuch'], { topics: ['hoa-am-cromatic'] }),
  c('Gustav Mahler', '1860–1911', 'Áo', 'rom:german', 'Giao hưởng khổng lồ "chứa đựng cả thế giới"; nhạc trưởng lừng danh.', ['Giao hưởng số 2 "Phục sinh", số 5, số 9', 'Das Lied von der Erde'], { short: 'Mahler' }),
  c('Richard Strauss', '1864–1949', 'Đức', 'rom:german', 'Thơ giao hưởng và opera với dàn nhạc rực rỡ.', ['Also sprach Zarathustra', 'Salome', 'Der Rosenkavalier', 'Vier letzte Lieder']),
  c('Alexander Zemlinsky', '1871–1942', 'Áo', 'rom:german', 'Thầy và anh vợ của Schoenberg, phong cách hậu Lãng mạn.', ['Lyrische Symphonie']),
  c('Max Reger', '1873–1916', 'Đức', 'rom:german', 'Đối âm Bach kết hợp hoà âm cromatic dày đặc.', ['Biến tấu và fugue chủ đề Mozart'], { topics: ['fugue', 'hoa-am-cromatic'] }),
  c('César Franck', '1822–1890', 'Bỉ – Pháp', 'rom:france', 'Nhạc sĩ organ; hình thức chu kỳ (chủ đề trở lại qua các chương).', ['Sonata violin La trưởng', 'Giao hưởng Rê thứ', 'Panis angelicus'], { short: 'Franck', topics: ['motif'] }),
  c('Édouard Lalo', '1823–1892', 'Pháp', 'rom:france', 'Nổi tiếng với tác phẩm violin mang màu sắc Tây Ban Nha.', ['Symphonie espagnole']),
  c('Camille Saint-Saëns', '1835–1921', 'Pháp', 'rom:france', 'Thần đồng đa tài, phong cách trong sáng.', ['Lễ hội muôn thú', 'Giao hưởng số 3 "Organ"', 'Danse macabre', 'Concerto piano số 2'], { short: 'Saint-Saëns' }),
  c('Léo Delibes', '1836–1891', 'Pháp', 'rom:france', 'Ballet và opera trữ tình.', ['Coppélia', 'Lakmé (Song ca hoa)']),
  c('Emmanuel Chabrier', '1841–1894', 'Pháp', 'rom:france', 'Màu sắc dàn nhạc rực rỡ, ảnh hưởng tới Debussy và Ravel.', ['España']),
  c('Charles-Marie Widor', '1844–1937', 'Pháp', 'rom:france', 'Nhạc sĩ organ Saint-Sulpice; viết giao hưởng cho organ.', ['Toccata (Giao hưởng organ số 5)']),
  c('Gabriel Fauré', '1845–1924', 'Pháp', 'rom:france', 'Hoà âm tinh tế, điệu thức; thầy của Ravel.', ['Requiem', 'Pavane', 'Après un rêve', 'Nocturne và Barcarolle cho piano'], { short: 'Fauré', topics: ['dieu-thuc'] }),
  c('Vincent d\'Indy', '1851–1931', 'Pháp', 'rom:france', 'Học trò Franck, đồng sáng lập Schola Cantorum Paris.', ['Symphonie sur un chant montagnard français']),
  c('Ernest Chausson', '1855–1899', 'Pháp', 'rom:france', 'Phong cách trữ tình giữa Franck và Debussy.', ['Poème cho violin và dàn nhạc']),
  c('Cécile Chaminade', '1857–1944', 'Pháp', 'rom:france', 'Tiểu phẩm piano rất được yêu thích; nữ nhà soạn nhạc đầu tiên nhận Bắc Đẩu Bội tinh.', ['Concertino cho sáo', 'Scarf Dance']),
  c('Mikhail Glinka', '1804–1857', 'Nga', 'rom:russia', '"Cha đẻ âm nhạc cổ điển Nga".', ['Ruslan và Lyudmila', 'Một đời vì Sa hoàng', 'Kamarinskaya']),
  c('Anton Rubinstein', '1829–1894', 'Nga', 'rom:russia', 'Nghệ sĩ piano lừng danh, sáng lập Nhạc viện St. Petersburg.', ['Melody in F', 'Concerto piano số 4']),
  c('Alexander Borodin', '1833–1887', 'Nga', 'rom:russia', 'Nhà hoá học kiêm nhà soạn nhạc, thành viên "Nhóm Năm người".', ['Hoàng tử Igor (Vũ khúc Polovtsian)', 'Tứ tấu đàn dây số 2']),
  c('César Cui', '1835–1918', 'Nga', 'rom:russia', 'Thành viên "Nhóm Năm người", nhà phê bình.', ['Orientale']),
  c('Mily Balakirev', '1837–1910', 'Nga', 'rom:russia', 'Thủ lĩnh "Nhóm Năm người".', ['Islamey (fantasy phương Đông cho piano)']),
  c('Modest Mussorgsky', '1839–1881', 'Nga', 'rom:russia', 'Phong cách độc đáo, hoà âm táo bạo, gần ngôn ngữ nói tiếng Nga.', ['Bức tranh triển lãm', 'Boris Godunov', 'Đêm trên núi trọc'], { short: 'Mussorgsky', topics: ['nhip-hon-hop', 'dieu-thuc'] }),
  c('Pyotr Ilyich Tchaikovsky', '1840–1893', 'Nga', 'rom:russia', 'Giai điệu đầy cảm xúc, dàn nhạc rực rỡ; ballet kinh điển.', ['Hồ Thiên Nga', 'Kẹp hạt dẻ', 'Concerto piano số 1', 'Giao hưởng số 6 "Pathétique"', 'Album cho thiếu nhi Op. 39'], { short: 'Tchaikovsky', topics: ['so-chi-nhip', 'nhip-hon-hop'] }),
  c('Nikolai Rimsky-Korsakov', '1844–1908', 'Nga', 'rom:russia', 'Bậc thầy phối khí, dùng âm giai bát cung; thầy của Stravinsky.', ['Scheherazade', 'Chuyến bay của ong nghệ', 'Capriccio espagnol'], { short: 'Rimsky-Korsakov', topics: ['am-giai-bat-cung'] }),
  c('Anatoly Lyadov', '1855–1914', 'Nga', 'rom:russia', 'Tiểu phẩm dàn nhạc và piano tinh xảo.', ['Kikimora', 'Hộp nhạc (Музыкальная табакерка)']),
  c('Alexander Glazunov', '1865–1936', 'Nga', 'rom:russia', 'Học trò Rimsky-Korsakov, giám đốc Nhạc viện St. Petersburg.', ['Concerto violin', 'Raymonda']),
  c('Sergei Rachmaninoff', '1873–1943', 'Nga', 'rom:russia', 'Nghệ sĩ piano huyền thoại; giai điệu Lãng mạn rộng lớn trong thế kỷ 20.', ['Concerto piano số 2 và 3', 'Rhapsody on a Theme of Paganini', 'Prélude Đô♯ thứ', 'Vespers'], { short: 'Rachmaninoff', topics: ['bien-tau'] }),
  c('Stanisław Moniuszko', '1819–1872', 'Ba Lan', 'rom:national', 'Cha đẻ opera dân tộc Ba Lan.', ['Halka', 'Straszny dwór']),
  c('Bedřich Smetana', '1824–1884', 'Séc', 'rom:national', 'Người sáng lập âm nhạc dân tộc Séc.', ['Má vlast (Tổ quốc tôi — "Vltava")', 'Cô dâu bị bán'], { short: 'Smetana' }),
  c('Henryk Wieniawski', '1835–1880', 'Ba Lan', 'rom:national', 'Nghệ sĩ violin điêu luyện.', ['Concerto violin số 2', 'Légende']),
  c('Antonín Dvořák', '1841–1904', 'Séc', 'rom:national', 'Kết hợp dân ca Séc (và cảm hứng Mỹ) với truyền thống Brahms.', ['Giao hưởng số 9 "Từ Tân Thế giới"', 'Concerto cello', 'Humoresque', 'Vũ khúc Slav'], { short: 'Dvořák', topics: ['am-giai-ngu-cung'] }),
  c('Edvard Grieg', '1843–1907', 'Na Uy', 'rom:national', 'Đưa dân ca Na Uy vào tiểu phẩm piano và dàn nhạc.', ['Peer Gynt ("Buổi sáng", "Trong cung điện vua núi")', 'Concerto piano La thứ', 'Lyric Pieces'], { short: 'Grieg', topics: ['the-loai'] }),
  c('Pablo de Sarasate', '1844–1908', 'Tây Ban Nha', 'rom:national', 'Nghệ sĩ violin điêu luyện, nhạc mang màu sắc Tây Ban Nha và Di-gan.', ['Zigeunerweisen', 'Carmen Fantasy']),
  c('Zdeněk Fibich', '1850–1900', 'Séc', 'rom:national', 'Nổi tiếng với chu kỳ tiểu phẩm piano mang tính nhật ký.', ['Poème (Nálady, dojmy a upomínky)']),
  c('Isaac Albéniz', '1860–1909', 'Tây Ban Nha', 'rom:national', 'Piano mang tinh thần flamenco và dân ca Tây Ban Nha.', ['Iberia', 'Asturias (Leyenda)'], { topics: ['dieu-thuc'] }),
  c('Jean Sibelius', '1865–1957', 'Phần Lan', 'rom:national', 'Biểu tượng dân tộc Phần Lan; giao hưởng phát triển từ những motif nhỏ.', ['Finlandia', '7 giao hưởng', 'Concerto violin'], { short: 'Sibelius', topics: ['motif'] }),
  c('Carl Nielsen', '1865–1931', 'Đan Mạch', 'rom:national', 'Nhà soạn nhạc Đan Mạch quan trọng nhất; giao hưởng với "điệu tính tiến triển".', ['Giao hưởng số 4 "Không thể dập tắt"', 'Concerto clarinet']),
  c('Enrique Granados', '1867–1916', 'Tây Ban Nha', 'rom:national', 'Piano lấy cảm hứng từ hội hoạ Goya.', ['Goyescas', 'Danzas españolas']),
  c('Louis Moreau Gottschalk', '1829–1869', 'Mỹ', 'rom:americas', 'Nghệ sĩ piano Mỹ đầu tiên nổi tiếng quốc tế, dùng nhịp điệu Creole và Caribe.', ['Bamboula', 'Souvenir de Porto Rico'], { topics: ['dao-phach'] }),
  c('Hubert Parry', '1848–1918', 'Anh', 'rom:americas', 'Nhà soạn nhạc và nhà giáo dục, linh hồn phục hưng âm nhạc Anh.', ['Jerusalem', 'I was glad']),
  c('Charles Villiers Stanford', '1852–1924', 'Ireland – Anh', 'rom:americas', 'Thầy của Vaughan Williams, Holst và cả một thế hệ nhạc sĩ Anh.', ['Các bài thánh ca Anh giáo', 'The Blue Bird']),
  c('Edward Elgar', '1857–1934', 'Anh', 'rom:americas', 'Nhà soạn nhạc Anh vĩ đại đầu tiên sau Purcell.', ['Enigma Variations', 'Pomp and Circumstance', 'Concerto cello'], { short: 'Elgar', topics: ['bien-tau'] }),
  c('Edward MacDowell', '1860–1908', 'Mỹ', 'rom:americas', 'Tiểu phẩm piano trữ tình theo phong cách Lãng mạn châu Âu.', ['Woodland Sketches ("To a Wild Rose")']),
  c('Amy Beach', '1867–1944', 'Mỹ', 'rom:americas', 'Nữ nhà soạn nhạc Mỹ đầu tiên thành công với các tác phẩm quy mô lớn.', ['Giao hưởng "Gaelic"', 'Concerto piano']),

  // ── Thế kỷ 20 ──
  c('Claude Debussy', '1862–1918', 'Pháp', 'm20:impressionism', 'Người mở ra âm nhạc thế kỷ 20: hoà âm ấn tượng, âm giai toàn cung và ngũ cung.', ['Prélude à l\'après-midi d\'un faune', 'La mer', 'Clair de lune', '24 Préludes', 'Children\'s Corner'], { short: 'Debussy', topics: ['an-tuong', 'am-giai-cromatic', 'am-giai-ngu-cung', 'hoa-am-quang-bon'] }),
  c('Erik Satie', '1866–1925', 'Pháp', 'm20:impressionism', 'Giản dị, hài hước, tiền thân của tối giản.', ['Gymnopédies', 'Gnossiennes', 'Vexations'], { short: 'Satie', topics: ['toi-gian', 'so-chi-nhip'] }),
  c('Paul Dukas', '1865–1935', 'Pháp', 'm20:impressionism', 'Bậc thầy phối khí, thầy của Messiaen.', ['L\'apprenti sorcier (Người học việc phù thuỷ)']),
  c('Albert Roussel', '1869–1937', 'Pháp', 'm20:impressionism', 'Từ ấn tượng chuyển sang tân cổ điển.', ['Bacchus et Ariane']),
  c('Maurice Ravel', '1875–1937', 'Pháp', 'm20:impressionism', 'Bậc thầy phối khí và piano với hình thức chuẩn xác.', ['Boléro', 'Pavane pour une infante défunte', 'Gaspard de la nuit', 'Jeux d\'eau', 'Concerto piano Sol trưởng'], { short: 'Ravel', topics: ['an-tuong', 'ostinato', 'hop-am-mo-rong'] }),
  c('Nadia Boulanger', '1887–1979', 'Pháp', 'm20:impressionism', 'Người thầy âm nhạc có ảnh hưởng nhất thế kỷ 20 (Copland, Glass, Piazzolla, Quincy Jones…).', ['Trois pièces cho cello và piano']),
  c('Lili Boulanger', '1893–1918', 'Pháp', 'm20:impressionism', 'Em gái Nadia; phụ nữ đầu tiên đoạt giải Prix de Rome về sáng tác.', ['D\'un matin de printemps', 'Psaume 130']),
  c('Arnold Schoenberg', '1874–1951', 'Áo – Mỹ', 'm20:vienna2', 'Đưa âm nhạc đến phi điệu tính rồi sáng tạo kỹ thuật 12 âm; nhà sư phạm lớn.', ['Verklärte Nacht', 'Pierrot lunaire', 'Suite cho piano Op. 25', 'Klavierstück Op. 33a', 'Harmonielehre (sách hoà âm)'], { short: 'Schoenberg', topics: ['phi-dieu-tinh', 'ky-thuat-12-am', 'hoa-am-cromatic'] }),
  c('Anton Webern', '1883–1945', 'Áo', 'm20:vienna2', 'Học trò Schoenberg; tác phẩm cực ngắn, cô đọng, ảnh hưởng tới chủ nghĩa chuỗi toàn phần.', ['Variationen Op. 27 cho piano', 'Giao hưởng Op. 21'], { short: 'Webern', topics: ['ky-thuat-12-am', 'doi-am-kep'] }),
  c('Alban Berg', '1885–1935', 'Áo', 'm20:vienna2', 'Học trò Schoenberg; dùng 12 âm nhưng vẫn giàu chất trữ tình.', ['Wozzeck', 'Lulu', 'Concerto violin', 'Lyric Suite'], { short: 'Berg', topics: ['ky-thuat-12-am'] }),
  c('Hanns Eisler', '1898–1962', 'Đức – Áo', 'm20:vienna2', 'Học trò Schoenberg, viết nhạc chính trị và nhạc phim.', ['Deutsche Sinfonie', 'Quốc ca Cộng hoà Dân chủ Đức']),
  c('Ernst Krenek', '1900–1991', 'Áo – Mỹ', 'm20:vienna2', 'Từ opera jazz đến kỹ thuật 12 âm.', ['Jonny spielt auf']),
  c('Alexander Scriabin', '1872–1915', 'Nga', 'm20:russia', 'Từ Lãng mạn kiểu Chopin đến hoà âm thần bí; "hợp âm huyền bí" dựng trên quãng 4.', ['Sonata piano số 5 và 9', 'Poème de l\'extase', 'Prometheus'], { short: 'Scriabin', topics: ['hoa-am-quang-bon'] }),
  c('Nikolai Medtner', '1880–1951', 'Nga', 'm20:russia', 'Nghệ sĩ piano – nhà soạn nhạc, phong cách Lãng mạn với đối âm chặt chẽ.', ['Skazki (Truyện cổ tích)', 'Sonata "Night Wind"']),
  c('Igor Stravinsky', '1882–1971', 'Nga – Mỹ', 'm20:russia', 'Một trong những nhà soạn nhạc quan trọng nhất thế kỷ 20: nguyên thuỷ, tân cổ điển, rồi 12 âm.', ['Le sacre du printemps', 'Petrushka', 'L\'oiseau de feu', 'Pulcinella', 'Symphony of Psalms'], { short: 'Stravinsky', topics: ['nhip-hon-hop', 'da-dieu-tinh', 'am-giai-bat-cung', 'ostinato'] }),
  c('Sergei Prokofiev', '1891–1953', 'Nga', 'm20:russia', 'Giai điệu sắc sảo, hài hước, nhịp điệu "cơ khí".', ['Pierre và chó sói', 'Romeo và Juliet', 'Giao hưởng Cổ điển', 'Sonata piano số 7'], { short: 'Prokofiev' }),
  c('Aram Khachaturian', '1903–1978', 'Armenia', 'm20:russia', 'Âm nhạc Xô Viết mang màu sắc dân gian Armenia.', ['Spartacus', 'Gayane ("Vũ điệu kiếm")', 'Valse trong Masquerade']),
  c('Dmitry Kabalevsky', '1904–1987', 'Nga', 'm20:russia', 'Nhà giáo dục âm nhạc; nhiều tiểu phẩm piano cho thiếu nhi là giáo trình phổ biến.', ['24 Tiểu phẩm thiếu nhi Op. 39', 'The Comedians']),
  c('Dmitri Shostakovich', '1906–1975', 'Nga', 'm20:russia', '15 giao hưởng và 15 tứ tấu phản ánh thời đại Xô Viết; châm biếm và bi tráng.', ['Giao hưởng số 5 và 7 "Leningrad"', '24 Prelude và Fugue Op. 87', 'Valse số 2', 'Tứ tấu đàn dây số 8'], { short: 'Shostakovich', topics: ['fugue', 'motif'] }),
  c('Mieczysław Weinberg', '1919–1996', 'Ba Lan – Nga', 'm20:russia', 'Bạn thân của Shostakovich; 22 giao hưởng, 17 tứ tấu.', ['The Passenger']),
  c('Galina Ustvolskaya', '1919–2006', 'Nga', 'm20:russia', 'Học trò Shostakovich; âm nhạc khắc khổ, dữ dội với âm cụm.', ['6 Sonata piano'], { topics: ['am-cum'] }),
  c('Sofia Gubaidulina', '1931–2025', 'Nga – Đức', 'm20:russia', 'Âm nhạc mang tính tâm linh với cấu trúc dựa trên dãy số Fibonacci.', ['Offertorium', 'Chaconne cho piano'], { topics: ['ostinato'] }),
  c('Alfred Schnittke', '1934–1998', 'Nga – Đức', 'm20:russia', 'Phong cách "đa phong cách" (polystylism) pha trộn nhiều thời kỳ.', ['Concerto Grosso số 1', 'Suite in the Old Style']),
  c('Ottorino Respighi', '1879–1936', 'Ý', 'm20:neoclassical', 'Thơ giao hưởng về Rome, phối khí rực rỡ, khôi phục nhạc cổ.', ['Pini di Roma', 'Fontane di Roma', 'Antiche danze ed arie']),
  c('Bohuslav Martinů', '1890–1959', 'Séc', 'm20:neoclassical', 'Tân cổ điển với nhịp điệu dân gian Séc, hơn 400 tác phẩm.', ['Giao hưởng số 6', 'Concerto đôi']),
  c('Darius Milhaud', '1892–1974', 'Pháp', 'm20:neoclassical', 'Thành viên Les Six, bậc thầy đa điệu tính, chịu ảnh hưởng jazz và nhạc Brazil.', ['Le bœuf sur le toit', 'La création du monde', 'Saudades do Brasil', 'Scaramouche'], { short: 'Milhaud', topics: ['da-dieu-tinh'] }),
  c('Arthur Honegger', '1892–1955', 'Thuỵ Sĩ – Pháp', 'm20:neoclassical', 'Thành viên Les Six; nổi tiếng với tác phẩm mô tả đầu máy xe lửa.', ['Pacific 231', 'Le roi David']),
  c('Germaine Tailleferre', '1892–1983', 'Pháp', 'm20:neoclassical', 'Nữ thành viên duy nhất của Les Six.', ['Concertino cho đàn hạc']),
  c('Paul Hindemith', '1895–1963', 'Đức – Mỹ', 'm20:neoclassical', 'Nhạc sĩ đa năng, nhà sư phạm; xây dựng lý thuyết hoà âm riêng dựa trên quãng 4.', ['Mathis der Maler', 'Ludus tonalis (piano)', 'Unterweisung im Tonsatz (sách lý thuyết)'], { short: 'Hindemith', topics: ['hoa-am-quang-bon', 'fugue'] }),
  c('Carl Orff', '1895–1982', 'Đức', 'm20:neoclassical', 'Nhịp điệu nguyên sơ, ostinato; sáng lập phương pháp dạy nhạc Orff-Schulwerk cho trẻ em.', ['Carmina Burana', 'Schulwerk'], { short: 'Orff', topics: ['ostinato', 'am-giai-ngu-cung', 'phuong-phap-giao-duc-am-nhac'] }),
  c('Francis Poulenc', '1899–1963', 'Pháp', 'm20:neoclassical', 'Thành viên Les Six; giai điệu duyên dáng xen lẫn thánh nhạc sâu lắng.', ['Gloria', 'Dialogues des Carmélites', 'Sonata sáo'], { short: 'Poulenc' }),
  c('Georges Auric', '1899–1983', 'Pháp', 'm20:neoclassical', 'Thành viên Les Six, viết nhiều nhạc phim.', ['Nhạc phim "Moulin Rouge" (1952)']),
  c('Kurt Weill', '1900–1950', 'Đức – Mỹ', 'm20:neoclassical', 'Nhạc kịch sân khấu với Brecht, sau đó Broadway.', ['Die Dreigroschenoper ("Mack the Knife")']),
  c('Leoš Janáček', '1854–1928', 'Séc', 'm20:national', 'Giai điệu dựa trên ngữ điệu tiếng Séc; phần lớn kiệt tác viết sau tuổi 60.', ['Jenůfa', 'Sinfonietta', 'Trên lối mòn cỏ mọc (piano)'], { short: 'Janáček' }),
  c('Manuel de Falla', '1876–1946', 'Tây Ban Nha', 'm20:national', 'Nhà soạn nhạc Tây Ban Nha quan trọng nhất thế kỷ 20.', ['El amor brujo ("Vũ điệu lửa")', 'Noches en los jardines de España']),
  c('Ernest Bloch', '1880–1959', 'Thuỵ Sĩ – Mỹ', 'm20:national', 'Âm nhạc lấy cảm hứng từ văn hoá Do Thái.', ['Schelomo']),
  c('Béla Bartók', '1881–1945', 'Hungary', 'm20:national', 'Nhà sưu tầm dân ca, kết hợp nhịp lẻ và điệu thức dân gian với ngôn ngữ hiện đại; bộ Mikrokosmos là giáo trình piano.', ['Mikrokosmos', 'Concerto cho dàn nhạc', 'Music for Strings, Percussion and Celesta', 'Allegro barbaro', 'Vũ khúc dân gian Romania'], { short: 'Bartók', topics: ['nhip-hon-hop', 'dieu-thuc', 'am-cum', 'hoa-am-quang-bon'] }),
  c('George Enescu', '1881–1955', 'Romania', 'm20:national', 'Nghệ sĩ violin, nhà soạn nhạc, thầy của Menuhin.', ['Rhapsody Romania số 1', 'Œdipe']),
  c('Zoltán Kodály', '1882–1967', 'Hungary', 'm20:national', 'Nhà sưu tầm dân ca và nhà giáo dục; phương pháp Kodály (đọc nốt bằng solfège, ký hiệu tay).', ['Háry János', 'Psalmus Hungaricus', 'Sonata cello độc tấu'], { short: 'Kodály', topics: ['am-giai-ngu-cung', 'xuong-am', 'phuong-phap-giao-duc-am-nhac'] }),
  c('Karol Szymanowski', '1882–1937', 'Ba Lan', 'm20:national', 'Kết hợp ấn tượng, phương Đông và dân ca vùng núi Ba Lan.', ['Król Roger', 'Mazurka Op. 50']),
  c('Heitor Villa-Lobos', '1887–1959', 'Brazil', 'm20:national', 'Nhà soạn nhạc Mỹ Latinh nổi tiếng nhất, kết hợp Bach với âm nhạc Brazil.', ['Bachianas Brasileiras số 5', 'Chôros', 'Prelude cho guitar']),
  c('Carlos Chávez', '1899–1978', 'Mexico', 'm20:national', 'Kết hợp âm nhạc bản địa Mexico với ngôn ngữ hiện đại.', ['Sinfonía india']),
  c('Silvestre Revueltas', '1899–1940', 'Mexico', 'm20:national', 'Nhịp điệu sôi động, phối khí táo bạo.', ['Sensemayá', 'La noche de los Mayas']),
  c('Joaquín Rodrigo', '1901–1999', 'Tây Ban Nha', 'm20:national', 'Concerto guitar nổi tiếng nhất mọi thời đại.', ['Concierto de Aranjuez']),
  c('Alberto Ginastera', '1916–1983', 'Argentina', 'm20:national', 'Kết hợp vũ điệu gaucho với kỹ thuật hiện đại.', ['Danzas argentinas', 'Estancia'], { topics: ['hemiola'] }),
  c('Astor Piazzolla', '1921–1992', 'Argentina', 'm20:national', 'Sáng tạo "tango nuevo" kết hợp tango, jazz và cổ điển.', ['Libertango', 'Adiós Nonino', 'Las cuatro estaciones porteñas'], { topics: ['dao-phach'] }),
  c('Frederick Delius', '1862–1934', 'Anh', 'm20:britain', 'Hoà âm cromatic mơ màng, gần với ấn tượng.', ['On Hearing the First Cuckoo in Spring']),
  c('Ralph Vaughan Williams', '1872–1958', 'Anh', 'm20:britain', 'Phục hưng dân ca và nhạc Tudor Anh, giàu điệu thức.', ['Fantasia on a Theme by Thomas Tallis', 'The Lark Ascending', '9 giao hưởng'], { short: 'Vaughan Williams', topics: ['dieu-thuc'] }),
  c('Gustav Holst', '1874–1934', 'Anh', 'm20:britain', 'Bộ tổ khúc "Các hành tinh" với "Sao Hoả" ở nhịp 5/4.', ['The Planets', 'St Paul\'s Suite'], { short: 'Holst', topics: ['nhip-hon-hop', 'ostinato'] }),
  c('William Walton', '1902–1983', 'Anh', 'm20:britain', 'Nhịp điệu sắc nét, giai điệu trang trọng.', ['Belshazzar\'s Feast', 'Façade', 'Crown Imperial']),
  c('Michael Tippett', '1905–1998', 'Anh', 'm20:britain', 'Đa dạng phong cách, chịu ảnh hưởng blues và spirituals.', ['A Child of Our Time']),
  c('Benjamin Britten', '1913–1976', 'Anh', 'm20:britain', 'Nhà soạn opera Anh quan trọng nhất thế kỷ 20.', ['Peter Grimes', 'War Requiem', 'The Young Person\'s Guide to the Orchestra'], { short: 'Britten', topics: ['bien-tau', 'fugue'] }),
  c('Scott Joplin', 'k. 1868–1917', 'Mỹ', 'm20:america', '"Vua ragtime" — đảo phách tay phải trên bè trầm stride tay trái.', ['Maple Leaf Rag', 'The Entertainer', 'Treemonisha'], { short: 'Joplin', topics: ['dao-phach', 'ket-cau'] }),
  c('Charles Ives', '1874–1954', 'Mỹ', 'm20:america', 'Nhà cách tân cô độc: đa điệu tính, âm cụm, trích dẫn nhạc dân gian Mỹ.', ['The Unanswered Question', 'Concord Sonata', 'Three Places in New England'], { short: 'Ives', topics: ['da-dieu-tinh', 'am-cum'] }),
  c('Edgard Varèse', '1883–1965', 'Pháp – Mỹ', 'm20:america', '"Âm thanh có tổ chức"; tiên phong nhạc điện tử và bộ gõ.', ['Ionisation', 'Poème électronique']),
  c('Florence Price', '1887–1953', 'Mỹ', 'm20:america', 'Nữ nhà soạn nhạc da đen đầu tiên có giao hưởng được một dàn nhạc lớn của Mỹ trình diễn.', ['Giao hưởng số 1 Mi thứ', 'Fantasie nègre']),
  c('William Grant Still', '1895–1978', 'Mỹ', 'm20:america', '"Trưởng lão" của các nhà soạn nhạc người Mỹ gốc Phi, kết hợp blues với giao hưởng.', ['Giao hưởng "Afro-American"'], { topics: ['am-giai-blues'] }),
  c('Henry Cowell', '1897–1965', 'Mỹ', 'm20:america', 'Tiên phong âm cụm và kỹ thuật chơi trực tiếp lên dây đàn piano.', ['The Tides of Manaunaun', 'The Banshee'], { short: 'Cowell', topics: ['am-cum'] }),
  c('George Gershwin', '1898–1937', 'Mỹ', 'm20:america', 'Kết hợp jazz và nhạc cổ điển; ca khúc của ông là jazz standard.', ['Rhapsody in Blue', 'Porgy and Bess ("Summertime")', 'An American in Paris', 'I Got Rhythm'], { short: 'Gershwin', topics: ['hinh-thuc-ca-khuc-32', 'am-giai-blues'] }),
  c('Duke Ellington', '1899–1974', 'Mỹ', 'm20:america', 'Nhà soạn nhạc jazz vĩ đại nhất, hơn 1.000 tác phẩm cho big band.', ['Mood Indigo', 'Take the "A" Train (Billy Strayhorn)', 'In a Sentimental Mood'], { short: 'Ellington', topics: ['swing', 'xep-hop-am'] }),
  c('Aaron Copland', '1900–1990', 'Mỹ', 'm20:america', 'Tạo nên "âm thanh nước Mỹ" với hoà âm rộng mở, quãng 4 – 5 trống.', ['Appalachian Spring', 'Fanfare for the Common Man', 'Rodeo'], { short: 'Copland', topics: ['hoa-am-quang-bon'] }),
  c('Ruth Crawford Seeger', '1901–1953', 'Mỹ', 'm20:america', 'Nhà hiện đại chủ nghĩa và nhà sưu tầm dân ca Mỹ.', ['String Quartet 1931']),
  c('Elliott Carter', '1908–2012', 'Mỹ', 'm20:america', 'Nổi tiếng với "điều chế nhịp độ" (metric modulation) và đa nhịp phức tạp.', ['Tứ tấu đàn dây', 'Night Fantasies'], { topics: ['da-nhip', 'nhip-do'] }),
  c('Samuel Barber', '1910–1981', 'Mỹ', 'm20:america', 'Phong cách tân Lãng mạn trữ tình.', ['Adagio for Strings', 'Knoxville: Summer of 1915', 'Sonata piano']),
  c('Leonard Bernstein', '1918–1990', 'Mỹ', 'm20:america', 'Nhạc trưởng, nhà giáo dục và nhà soạn nhạc giao thoa Broadway – cổ điển.', ['West Side Story', 'Candide', 'Chichester Psalms'], { short: 'Bernstein', topics: ['hemiola', 'nhip-hon-hop'] }),
  c('Dave Brubeck', '1920–2012', 'Mỹ', 'm20:america', 'Nghệ sĩ piano jazz phổ biến nhịp lẻ.', ['Take Five (Paul Desmond)', 'Blue Rondo à la Turk'], { topics: ['nhip-hon-hop'] }),
  c('Olivier Messiaen', '1908–1992', 'Pháp', 'm20:avantgarde', 'Điệu thức chuyển vị giới hạn, tiếng chim, nhịp điệu Ấn Độ; thầy của Boulez và Stockhausen.', ['Quatuor pour la fin du temps', 'Turangalîla-Symphonie', 'Vingt regards sur l\'Enfant-Jésus', 'Catalogue d\'oiseaux'], { short: 'Messiaen', topics: ['am-giai-bat-cung', 'nhip-hon-hop', 'ky-thuat-12-am'] }),
  c('John Cage', '1912–1992', 'Mỹ', 'm20:avantgarde', 'Âm nhạc ngẫu nhiên, piano chuẩn bị (prepared piano); "4′33″" đặt lại câu hỏi âm nhạc là gì.', ['4′33″', 'Sonatas and Interludes cho prepared piano', 'In a Landscape'], { short: 'Cage' }),
  c('Witold Lutosławski', '1913–1994', 'Ba Lan', 'm20:avantgarde', 'Kỹ thuật "ngẫu nhiên có kiểm soát".', ['Concerto cho dàn nhạc', 'Giao hưởng số 3']),
  c('Henri Dutilleux', '1916–2013', 'Pháp', 'm20:avantgarde', 'Phong cách tinh tế, độc lập với các trào lưu.', ['Tout un monde lointain', 'Métaboles']),
  c('Isang Yun', '1917–1995', 'Hàn Quốc – Đức', 'm20:avantgarde', 'Kết hợp âm nhạc cung đình Hàn Quốc với kỹ thuật tiên phong phương Tây.', ['Réak']),
  c('Bernd Alois Zimmermann', '1918–1970', 'Đức', 'm20:avantgarde', 'Kỹ thuật cắt dán (collage) trích dẫn nhiều thời kỳ.', ['Die Soldaten']),
  c('Iannis Xenakis', '1922–2001', 'Hy Lạp – Pháp', 'm20:avantgarde', 'Kiến trúc sư – nhà soạn nhạc, dùng toán học xác suất để sáng tác.', ['Metastaseis', 'Evryali (piano)']),
  c('György Ligeti', '1923–2006', 'Hungary – Áo', 'm20:avantgarde', 'Kết cấu âm cụm "micropolyphony"; Études piano là kiệt tác thế kỷ 20.', ['Atmosphères', 'Lux aeterna', 'Études cho piano', 'Musica ricercata'], { short: 'Ligeti', topics: ['am-cum', 'da-nhip'] }),
  c('Luigi Nono', '1924–1990', 'Ý', 'm20:avantgarde', 'Chủ nghĩa chuỗi gắn với dấn thân chính trị.', ['Il canto sospeso']),
  c('Pierre Boulez', '1925–2016', 'Pháp', 'm20:avantgarde', 'Thủ lĩnh chủ nghĩa chuỗi toàn phần, nhạc trưởng lừng danh, sáng lập IRCAM.', ['Le marteau sans maître', 'Structures', 'Sonata piano số 2'], { short: 'Boulez', topics: ['ky-thuat-12-am'] }),
  c('Luciano Berio', '1925–2003', 'Ý', 'm20:avantgarde', 'Chuỗi tác phẩm độc tấu Sequenza; nhạc điện tử và cắt dán.', ['Sinfonia', 'Sequenza']),
  c('Morton Feldman', '1926–1987', 'Mỹ', 'm20:avantgarde', 'Âm nhạc rất nhỏ, rất chậm và rất dài.', ['Rothko Chapel', 'Triadic Memories (piano)']),
  c('Hans Werner Henze', '1926–2012', 'Đức', 'm20:avantgarde', 'Nhà soạn opera và giao hưởng sung sức, phong cách tự do.', ['Elegy for Young Lovers']),
  c('Karlheinz Stockhausen', '1928–2007', 'Đức', 'm20:avantgarde', 'Tiên phong nhạc điện tử, chủ nghĩa chuỗi và âm nhạc không gian.', ['Gesang der Jünglinge', 'Klavierstücke', 'Licht']),
  c('George Crumb', '1929–2022', 'Mỹ', 'm20:avantgarde', 'Âm sắc mới trên piano (gảy dây, chạm dây) và ký âm hình ảnh.', ['Makrokosmos', 'Black Angels', 'Ancient Voices of Children'], { topics: ['chuoi-boi-am'] }),
  c('Toru Takemitsu', '1930–1996', 'Nhật Bản', 'm20:avantgarde', 'Kết hợp thẩm mỹ Nhật với ấn tượng Pháp; nhạc phim Kurosawa.', ['November Steps', 'Rain Tree Sketch'], { topics: ['an-tuong'] }),
  c('Mauricio Kagel', '1931–2008', 'Argentina – Đức', 'm20:avantgarde', 'Nhạc kịch sân khấu hài hước, thử nghiệm.', ['Staatstheater', 'Ludwig van']),
  c('Krzysztof Penderecki', '1933–2020', 'Ba Lan', 'm20:avantgarde', 'Khối âm cụm dàn dây; về sau chuyển sang tân Lãng mạn.', ['Threnody for the Victims of Hiroshima', 'St Luke Passion'], { short: 'Penderecki', topics: ['am-cum'] }),
  c('Gérard Grisey', '1946–1998', 'Pháp', 'm20:avantgarde', 'Sáng lập âm nhạc phổ âm (spectralism), xây hoà âm từ chuỗi bồi âm.', ['Les espaces acoustiques', 'Partiels'], { topics: ['chuoi-boi-am'] }),
  c('Tristan Murail', '1947–', 'Pháp', 'm20:avantgarde', 'Đồng sáng lập âm nhạc phổ âm.', ['Gondwana', 'Territoires de l\'oubli (piano)'], { topics: ['chuoi-boi-am'] }),
  c('Kaija Saariaho', '1952–2023', 'Phần Lan', 'm20:avantgarde', 'Âm sắc tinh tế, kết hợp điện tử và nhạc cụ.', ['L\'amour de loin', 'Lichtbogen']),
  c('Henryk Górecki', '1933–2010', 'Ba Lan', 'm20:minimal', 'Từ tiên phong đến "tối giản thánh"; Giao hưởng số 3 bán hơn một triệu bản đĩa.', ['Giao hưởng số 3 "Những khúc ca buồn"'], { topics: ['toi-gian'] }),
  c('Arvo Pärt', '1935–', 'Estonia', 'm20:minimal', 'Phong cách "tintinnabuli": một bè đi theo âm giai, một bè rải hợp âm ba.', ['Spiegel im Spiegel', 'Für Alina', 'Fratres', 'Tabula rasa'], { short: 'Pärt', topics: ['toi-gian', 'hop-am-ba'] }),
  c('La Monte Young', '1935–', 'Mỹ', 'm20:minimal', 'Người khởi xướng tối giản với âm thanh ngân rất dài (drone).', ['The Well-Tuned Piano'], { topics: ['bass-ngan', 'luat-binh-quan'] }),
  c('Terry Riley', '1935–', 'Mỹ', 'm20:minimal', 'Tác phẩm "In C" (1964) mở ra trào lưu tối giản.', ['In C', 'A Rainbow in Curved Air'], { topics: ['toi-gian'] }),
  c('Steve Reich', '1936–', 'Mỹ', 'm20:minimal', 'Kỹ thuật lệch pha (phasing) và nhịp điệu lặp lại tinh vi.', ['Piano Phase', 'Music for 18 Musicians', 'Clapping Music', 'Different Trains'], { short: 'Steve Reich', topics: ['toi-gian', 'da-nhip'] }),
  c('Philip Glass', '1937–', 'Mỹ', 'm20:minimal', 'Quá trình cộng và ostinato rải hợp âm; opera, nhạc phim và piano.', ['Einstein on the Beach', 'Metamorphosis', 'Glassworks', 'Koyaanisqatsi'], { short: 'Philip Glass', topics: ['toi-gian', 'ostinato'] }),
  c('Louis Andriessen', '1939–2021', 'Hà Lan', 'm20:minimal', 'Tối giản mạnh mẽ chịu ảnh hưởng Stravinsky và jazz.', ['De Staat', 'Hoketus']),
  c('John Tavener', '1944–2013', 'Anh', 'm20:minimal', 'Thánh nhạc tĩnh lặng chịu ảnh hưởng Chính Thống giáo.', ['The Protecting Veil', 'Song for Athene']),
  c('Michael Nyman', '1944–', 'Anh', 'm20:minimal', 'Tối giản với vòng hợp âm Baroque; nhạc phim "The Piano".', ['The Heart Asks Pleasure First']),
  c('John Adams', '1947–', 'Mỹ', 'm20:minimal', 'Hậu tối giản với hoà âm phong phú và opera về sự kiện đương đại.', ['Nixon in China', 'Short Ride in a Fast Machine', 'Harmonielehre'], { topics: ['toi-gian'], wiki: 'John_Adams_(composer)' }),
  c('Erich Wolfgang Korngold', '1897–1957', 'Áo – Mỹ', 'm20:film', 'Thần đồng Vienna, đặt nền móng cho nhạc phim Hollywood.', ['The Adventures of Robin Hood', 'Concerto violin', 'Die tote Stadt']),
  c('Nino Rota', '1911–1979', 'Ý', 'm20:film', 'Nhạc phim Fellini và "Bố già".', ['The Godfather', 'La strada', '8½']),
  c('Bernard Herrmann', '1911–1975', 'Mỹ', 'm20:film', 'Cộng sự của Hitchcock; dùng ostinato và hợp âm đặc trưng tạo căng thẳng.', ['Psycho', 'Vertigo', 'Citizen Kane'], { topics: ['ostinato', 'hop-am-bay'] }),
  c('Ennio Morricone', '1928–2020', 'Ý', 'm20:film', 'Hơn 400 nhạc phim, từ Western Ý đến "Cinema Paradiso".', ['The Good, the Bad and the Ugly', 'The Mission ("Gabriel\'s Oboe")', 'Cinema Paradiso']),
  c('John Williams', '1932–', 'Mỹ', 'm20:film', 'Nhà soạn nhạc phim nổi tiếng nhất; leitmotif kiểu Wagner, trung âm cromatic.', ['Star Wars', 'Jaws', 'E.T.', 'Harry Potter', 'Schindler\'s List'], { short: 'John Williams', topics: ['motif', 'trung-am-cromatic'], wiki: 'John_Williams' }),
  c('Joe Hisaishi', '1950–', 'Nhật Bản', 'm20:film', 'Nhạc phim Studio Ghibli của Hayao Miyazaki, chịu ảnh hưởng tối giản.', ['Spirited Away ("One Summer\'s Day")', 'My Neighbor Totoro', 'Howl\'s Moving Castle'], { topics: ['toi-gian'] }),
]

export const composers: Article[] = buildPeople(PERIODS, COMPOSERS, {
  category: 'composers',
  noun: 'nhà soạn nhạc',
  groupLabel: 'Trường phái',
  worksTitle: 'Tác phẩm tiêu biểu',
  footer: 'Tổng quan các thời kỳ và đặc trưng lý thuyết: [[cac-thoi-ky]].',
})
